=== MiquelAr-GD/DAM-Repository/M04/UF1/PE/a.dtd
<!ELEMENT zoo (animals)>
<!ELEMENT animals (animal*)>
<!ELEMENT animal (nomEspecie, cuidador)>
<!ELEMENT nomEspecie (#PCDATA)>
<!ELEMENT cuidador (nomCuidador, nomActivitat?, dataInici?)>
<!ELEMENT nomCuidador (#PCDATA)>
<!ELEMENT nomActivitat (#PCDATA)>
<!ELEMENT dataInici (#PCDATA)>
<!ATTLIST zoo titularidad ( public | privat ) "public">
<!ATTLIST animal xipUnic ID #REQUIRED>
<!ATTLIST animal mare IDREF #IMPLIED>

=== MiquelAr-GD/DAM-Repository/M04/UF1/PE/a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zoo SYSTEM "a.dtd">
<zoo titularidad="public">
   <animals>
     <animal xipUnic="a">
       <nomEspecie>
         El nom és: Pingüins
       </nomEspecie>
       <cuidador>
         <nomCuidador>
           El nom és: Marta
         </nomCuidador>
         <nomActivitat>
           Jugar a la pilota
         </nomActivitat>
       </cuidador>
     </animal>
     <animal xipUnic="b" mare="a">
       <nomEspecie>
         El nom és: Ossos polars
       </nomEspecie>
       <cuidador>
         <nomCuidador>
           El nom és: Guillem
         </nomCuidador>
         <dataInici>
           2008-02-04
         </dataInici>
       </cuidador>
     </animal>
    </animals>
</zoo>
