=== MiquelAr-GD/DAM-Repository/M04/UF1/UF1NF1A6_Activitats_DTDMiquelAndres/E1.dtd
<!ELEMENT biblioteca (llibres)>
 <!ELEMENT llibres (llibre*)>
 <!ELEMENT llibre (codi, titol, editorial, edicio, isbn, pag, autor)>
 <!ELEMENT codi (#PCDATA)>
 <!ELEMENT titol (#PCDATA)>
 <!ELEMENT editorial (#PCDATA)>
 <!ELEMENT edicio (#PCDATA)>
 <!ELEMENT isbn (#PCDATA)>
 <!ELEMENT pag (#PCDATA)>
 <!ELEMENT autor (#PCDATA)>

=== MiquelAr-GD/DAM-Repository/M04/UF1/UF1NF1A6_Activitats_DTDMiquelAndres/E1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "E1.dtd">
<biblioteca>
  <llibres>
    <llibre>
      <codi></codi>
      <titol></titol>
      <editorial></editorial>
      <edicio></edicio>
      <isbn></isbn>
      <pag></pag>
      <autor></autor>
    </llibre>  
  </llibres>
</biblioteca>
