=== MiquelAr-GD/DAM-Repository/M04/UF1/UF1NF1A6_Activitats_DTDMiquelAndres/E3.dtd
<!ELEMENT escala (vei*)>
<!ELEMENT vei (nom, cognoms, portal, pis, ccc, carrec)>
<!ATTLIST vei Codi ID #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognoms (#PCDATA)>
<!ELEMENT portal (#PCDATA)>
<!ELEMENT pis (#PCDATA)>
<!ATTLIST pis lletra CDATA #REQUIRED>
<!ELEMENT ccc (#PCDATA)>
<!ELEMENT carrec (#PCDATA)>

=== MiquelAr-GD/DAM-Repository/M04/UF1/UF1NF1A6_Activitats_DTDMiquelAndres/E3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escala SYSTEM "E3.dtd">
<escala>
  <vei Codi="_1">
  <nom>Manel</nom>
  <cognoms>Camps Ponts</cognoms>
  <portal>522</portal> 
  <pis lletra="A">5</pis>
  <ccc>123456789h</ccc>
  <carrec>Cap</carrec>
  </vei>
    <vei Codi="_2">
  <nom>Ainhoa</nom>
  <cognoms>Perez Gimenez</cognoms>
  <portal>522</portal> 
  <pis lletra="B">5</pis>
  <ccc>123456789j</ccc>
  <carrec>President</carrec>
  </vei>
    <vei Codi="_3">
  <nom>David</nom>
  <cognoms>Camps Ponts</cognoms>
  <portal>522</portal> 
  <pis lletra="A">4</pis>
  <ccc>123456789A</ccc>
  <carrec>Cap</carrec>
  </vei>
    <vei Codi="_4">
  <nom>Berta</nom>
  <cognoms>Morales Gomez</cognoms>
  <portal>522</portal> 
  <pis lletra="A">3</pis>
  <ccc>1234512389</ccc>
  <carrec>Vicepresident</carrec>
  </vei>
</escala>
