=== MiquelAr-GD/DAM-Repository/M04/UF1/UF1NF1A6_Activitats_DTDMiquelAndres/E4.dtd
<!ELEMENT concessionari (cotxe*)>
<!ELEMENT cotxe (marca, model, matricula, potencia, places, nportes)>
<!ATTLIST cotxe Codi ID #REQUIRED>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ATTLIST potencia unitat_mesura CDATA #REQUIRED>
<!ELEMENT places (#PCDATA)>
<!ELEMENT nportes (#PCDATA)>

=== MiquelAr-GD/DAM-Repository/M04/UF1/UF1NF1A6_Activitats_DTDMiquelAndres/E4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concessionari SYSTEM "E4.dtd">
<concessionari>
    <cotxe Codi="_1">
      <marca>Opel</marca>
      <model>Corsa</model>
      <matricula>1W4SA</matricula>
      <potencia unitat_mesura="caballs">150</potencia>
      <places>4</places>
      <nportes>4</nportes>
    </cotxe>
    <cotxe Codi="_2">
      <marca>BMW</marca>
      <model>Albaricoque</model>
      <matricula>1W4S3A</matricula>
      <potencia unitat_mesura="caballs">200</potencia>
      <places>4</places>
      <nportes>4</nportes>
    </cotxe>
    <cotxe Codi="_3">
      <marca>Mustang</marca>
      <model>69</model>
      <matricula>H3L1F1RE</matricula>
      <potencia unitat_mesura="caballs">800</potencia>
      <places>4</places>
      <nportes>2</nportes>
    </cotxe>
    <cotxe Codi="_4">
      <marca>BMW</marca>
      <model>A3</model>
      <matricula>123SAD</matricula>
      <potencia unitat_mesura="caballs">150</potencia>
      <places>4</places>
      <nportes>4</nportes>
    </cotxe>
</concessionari>
