=== MiquelAr-GD/DAM-Repository/M04/UF1/Exercici XSD/b.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="companyia-electrica">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="soci" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
                <xs:element name="nom" maxOccurs="unbounded"/>
                <xs:element name="cognoms">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="c" type="xs:string" maxOccurs="4"/>
                   </xs:sequence>
                </xs:complexType>
               </xs:element>
               <xs:element name="diners" type="xs:decimal" maxOccurs="unbounded"/>
            </xs:sequence>
         </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MiquelAr-GD/DAM-Repository/M04/UF1/Exercici XSD/b.xml
<?xml version="1.0" encoding="UTF-8"?>
<companyia-electrica   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="b.xsd">
<soci>
<nom>joan</nom>
<cognoms><c>caspar</c><c>fos</c></cognoms>
<diners>100.25</diners>
</soci>
<soci>
<nom>flor</nom>
<cognoms><c>fdez</c><c>artal</c></cognoms>
<diners>165449.58</diners>
</soci>
</companyia-electrica>
